version: "3"
services:
  # static:
  #   build:
  #     context: ./static
  #   volumes:
  #     - ./static/src:/srv/src
  #     - ./static/templete:/srv/templete
  #     - ./static/package.json:/srv/package.json
  #     - ./static/.eslintrc.js:/srv/.eslintrc.js
  #     - ./static/webpack.config.js:/srv/webpack.config.js
  #     - ./static/dist:/srv/dist

  flask:
    build:
      context: ./web
    # depends_on:
    #   - static
    expose:
      - "80"
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.pybibim-http.rule=Host(`pybibim.ov.update.sh`, `pybibim.update.sh`)"
      - "traefik.http.routers.pybibim-http.entrypoints=http"
      - "traefik.http.routers.pybibim-http.middlewares=https_redirect"
      - "traefik.http.routers.pybibim.rule=Host(`pybibim.ov.update.sh`, `pybibim.update.sh`)"
      - "traefik.http.routers.pybibim.entrypoints=https"
      - "traefik.http.routers.pybibim.tls=true"
      - "traefik.http.routers.pybibim.tls.certresolver=le"
      - "traefik.http.services.pybibim.loadbalancer.server.port=80"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
    volumes:
      - ./web/data/flask:/var/www/flask
      - ./web/data/flask.conf:/etc/nginx/sites-available/flask.conf:ro
      - ./web/data/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./web/data/log/uwsgi:/var/log/uwsgi
      - ./web/data/log/nginx:/var/log/nginx
      - ./static/dist:/var/www/flask/app/static
    restart: always

networks:
  default:
    driver: bridge
  traefik:
    external:
      name: traefik_proxy
